
# os: osx

# osx_image: xcode11.2

language: python

cache: pip

python:
  - "3.9.1"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
