
# os: osx

# osx_image: xcode11.2

language: python

cache: pip

python:
  - "3.7"

# command to install dependencies
install:
  # - pip install -r requirements.txt
  pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython

# command to run tests
script: ${TRAVIS_BUILD_DIR}/runtests.sh
